apiVersion: batch/v1
kind: CronJob
metadata:
  name: velotio-cronjob
  namespace: velotio-shruti
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helloworld
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello world
          restartPolicy: OnFailure
