apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: velotio-shruti
  labels:
    app: velotio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: velotio
  template:
    metadata:
      labels:
        app: velotio
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.8
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80

#kubectl set image deployment/nginx-deployment nginx=nginx:1.7.9 --namespace=velotio-shruti

#kubectl rollout status deployment/nginx-deployment --namespace=velotio-shruti

